# Generated by Django 5.2.14 on 2026-05-10 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_parent_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentprofile",
            name="parent",
            field=models.ForeignKey(
                limit_choices_to={"role": "parent"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_student_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
