# Generated by Django 5.2.13 on 2026-05-04 08:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("name_ar", models.CharField(max_length=120, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        choices=[
                            ("capital", "Capital"),
                            ("hawalli", "Hawalli"),
                            ("farwaniya", "Farwaniya"),
                            ("mubarak_al_kabeer", "Mubarak Al-Kabeer"),
                            ("ahmadi", "Ahmadi"),
                            ("jahra", "Jahra"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("mosque_name", models.CharField(max_length=160)),
                ("location_name", models.CharField(blank=True, max_length=160)),
                ("capacity", models.PositiveIntegerField(default=25)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["governorate", "gender", "name"],
            },
        ),
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=140)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "default_session_start_time",
                    models.TimeField(default=datetime.time(16, 0)),
                ),
                (
                    "default_session_end_time",
                    models.TimeField(default=datetime.time(18, 0)),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cycles",
                        to="circles.circle",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "circle__name"],
            },
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(
                fields=["governorate", "gender", "is_active"],
                name="circles_cir_governo_83acf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cycle",
            index=models.Index(
                fields=["status", "start_date", "end_date"],
                name="circles_cyc_status_46527f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cycle",
            constraint=models.UniqueConstraint(
                fields=("circle", "title"), name="unique_cycle_title_per_circle"
            ),
        ),
    ]
