# Generated by Django 5.2.14 on 2026-05-17 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("name_ar", models.CharField(max_length=120, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        choices=[
                            ("capital", "Capital"),
                            ("hawalli", "Hawalli"),
                            ("farwaniya", "Farwaniya"),
                            ("mubarak_al_kabeer", "Mubarak Al-Kabeer"),
                            ("ahmadi", "Ahmadi"),
                            ("jahra", "Jahra"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("mosque_name", models.CharField(max_length=160)),
                ("location_name", models.CharField(blank=True, max_length=160)),
                ("capacity", models.PositiveIntegerField(default=25)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_circles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["governorate", "gender", "name"],
                "indexes": [
                    models.Index(
                        fields=["governorate", "gender", "is_active"],
                        name="circles_cir_governo_83acf4_idx",
                    )
                ],
            },
        ),
    ]
