# Generated by Django 5.2.14 on 2026-05-17 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="circle",
            options={"ordering": ["governorate", "name"]},
        ),
        migrations.RemoveIndex(
            model_name="circle",
            name="circles_cir_governo_83acf4_idx",
        ),
        migrations.RenameField(
            model_name="circle",
            old_name="notes",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="location_name",
        ),
        migrations.RemoveField(
            model_name="circle",
            name="mosque_name",
        ),
        migrations.AddField(
            model_name="circle",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="circle",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="circles/"),
        ),
        migrations.AddField(
            model_name="circle",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="circle",
            name="status",
            field=models.CharField(
                choices=[("open", "مفتوحة"), ("closed", "مغلقة")],
                db_index=True,
                default="open",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(
                fields=["governorate", "gender", "status"],
                name="circles_cir_governo_cf3446_idx",
            ),
        ),
    ]
