# Generated by Django 5.2.14 on 2026-05-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0004_add_enrollment_withdrawal_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="removal_reason",
            field=models.TextField(blank=True),
        ),
    ]
